server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:33061/daoyun
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create
      # ddl-auto: none
      # ddl-auto: create-drop # DEV

redis:
  host: localhost
  port: 63791
  password: password

logging:
  level:
    root: INFO

jwt:
  secret: helloworld

# using environment variable
# AliyunAccessKeyId: 
# AliyunAccessKeySecret: 


daoyun:
  # super admin, just for testing api 
  # set HTTP Header 'X-IM_ADMIN: supersuper.name'
  supersuper:
    enable: true
    name: daoyun
  message:
    enable: true
    waitMs: 6000
    validMs: 300000
  reset:
    validMs: 300000
  aliyun:
    AliyunSmsSignName: 生意专家
    TemplateCode:
      login: SMS_205462496
      signup: SMS_205462496
      reset: SMS_205462496
      bindPhoneNum: SMS_205462496
  hcaptcha:
    allowNum: 3
    retainS: 300
    endpoint: https://hcaptcha.com/siteverify
    sitesecret: '0x77CFb863E1Fceb0139Ccd56dB08ffEA6584C67A6'

