server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:33061/daoyun
    username: root
    password: password

  jpa:
    hibernate:
      # ddl-auto: update
      # ddl-auto: create
      ddl-auto: none
      # ddl-auto: create-drop # DEV

redis:
  host: localhost
  port: 63791
  password: password

logging:
  level:
    root: INFO

jwt:
  secret: helloworld

daoyun:
  # super admin, just for testing api 
  # set HTTP Header 'X-IM_ADMIN: supersuper.name'
  supersuper:
    enable: true
    name: daoyun
  message:
    waitMs: 3000
    validMs: 300000

